name: endgame
description: "A streamlined app for checking stats for FIRST Robotics Competition events, teams, districts, and more."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  date_time_format: ^2.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  scaffold_gradient_background: ^1.0.3+1
  shared_preferences: ^2.2.3
  shimmer_pro: ^0.0.6
  toastification: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true