name: endgame
description: "A streamlined app for checking stats for FIRST Robotics Competition events, teams, districts., and more."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  date_time_format: ^2.0.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  scaffold_gradient_background: ^1.0.3+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
