name: Build Android
on: [push, pull_request, workflow_dispatch]

permissions: read-all

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Secrets File
        run: echo "class ApiSecrets { static const tbaKey = '${{ secrets.TBA_KEY }}'; }" > lib/src/services/api_secrets.dart

      - name: Generate Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Setup Java Environment        
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk
        
      - name: Build App Bundle
        run: flutter build appbundle