name: Docker Image Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set TBA_KEY environment variable
      env:
        TBA_KEY: ${{ secrets.TBA_KEY }}
      run: echo "::set-env name=TBA_KEY::${{ secrets.TBA_KEY }}"

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t endgame:$(date +%s)
