name: Docker Image Build
on: [push, pull_request, workflow_dispatch]

permissions: read-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t endgame:$(date +%s) --build-arg TBA_API_KEY=${{ secrets.TBA_API_KEY }}
