name: Flutter Analyze
on: [push, pull_request, workflow_dispatch]

permissions: read-all

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate api_secret.dart
        run: echo "class ApiSecrets { static const tbaKey = '${{ secrets.TBA_KEY }}'; }" > lib/src/services/api_secret.dart
          
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Run Flutter Analyze
        run: flutter analyze